[package]
name = "common_crate"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.7.0", default-features = false }

[[bench]]
name = "key_value"
harness = false
[[bench]]
name = "parse_array"
harness = false